apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policyscalers.extensions.example.com
spec:
  scope: Namespaced
  group: extensions.example.com
  names:
    plural: policyscalers
    singular: policyscaler
    kind: PolicyScaler
    shortNames:
    - pscaler
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              policies:
                type: object
                properties:
                  time:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        schedule:
                          type: string
                          description: "Cron expression (e.g., '0 9 * * MON-FRI')"
                          pattern: '^\d{1,2} \d{1,2} \* \* [\w\-,]+$'
                        replicas:
                          type: integer
                          description: "Number of replicas to scale to"
                        cpu:
                          type: object
                          properties:
                            request:
                              type: string
                            limit:
                              type: string
                        memory:
                          type: object
                          properties:
                            request:
                              type: string
                            limit:
                              type: string
                        storage:
                          type: object
                          properties:
                            request:
                              type: string
                      required:
                      - name
                      - schedule
              required:
              - policies




